### ISSUE TITLE
Assignment 6-  Pattern of *

### ISSUE THREAD

**Issue by 55bit23** [vtcbca/basic-programming-49bit23#3]
How can you align the stars in the center for a pattern?

**Comment by 49bit23** [comment]
You can use spaces before printing stars to center them on each line. Example:

`print(" " * (rows - i) + "* " * i)`

**Comment by 55bit23** [comment]
What is the role of end=" " in the print statement?

**Comment by 49bit23** [comment]
It prevents the print() function from starting a new line after printing a star. This keeps the stars on the same line.

**Comment by 55bit23** [comment]
How do you print the pattern in reverse order?

**Comment by 49bit23** [comment]
Change the loop to decrement the number of stars and start from the maximum number of rows.

**Comment by 55bit23** [comment]
How would you print a pyramid-like star pattern?

**Comment by 49bit23** [comment]
he pyramid pattern uses spaces before the stars on each row to center them:


`print(" " * (rows - i) + "* " * i)`

**Comment by 55bit23** [comment]
Can you print a pattern that increases the stars on one side and decreases on the other?

**Comment by 49bit23** [comment]
Yes, by first increasing the stars and then decreasing them in subsequent rows.

**Comment by 55bit23** [comment]
What happens if you forget to put end='' while printing the stars in a loop?

**Comment by 49bit23** [comment]
The stars will be printed on separate lines instead of on the same line.
